### PR TITLE
Honor dashboard filter default values on page load

### LINKED ISSUE #131: [Bug] Filter default values aren't applied to queries on initial dashboard load
### Elixir & OTP versions

Elixir 1.17.2 OTP 27

### Lotus & LotusWeb versions

{:lotus, "~> 0.16.1"},       {:lotus_web, "~> 0.14.0"}

### Phoenix version

phoenix 1.8.3 

### Phoenix LiveView version

phoenix_live_view 1.1.23

### Phoenix.HTML / Phoenix.Template versions

phoenix_html 4.3.0 phoenix_template 1.0.4

### Phoenix JS packages (assets)

_No response_

### OS and Browser

_No response_

### Node.js & package manager

_No response_

### Database & adapter (optional)

_No response_

### Steps to reproduce

When a dashboard filter is configured with a default value, the default is displayed in the filter widget on initial page load but is not passed to the mapped query variables. The query runs as if no value were provided. As soon as the user changes the filter value (including changing it and setting it back to the default), the value is passed correctly and thequery runs as expected.        

### What did you expect to happen?

I expect the default dashboard filter to be passed to the queries as mapped parameters on the initial page load. 

### What actually happened?

The default parameter was not passed to the queries. 

### Screenshots / screen recording (optional)

_No response_

### Confirm

- [x] I am using a **tagged release**, not the `main` branch.
- [x] I searched existing issues and discussions for this problem.

### PR DESCRIPTION
**Pull request by tugayac**
## Issue reference

- Fixes #131

## Changes

- Update `extract_filter_values/2` in `dashboard_editor_page.ex` and `public_dashboard_page.ex` to fall back to each filter's `default_value` when the corresponding query param is missing or blank
- Add a small `present/1` helper to treat empty strings as missing
- Add tests covering default-value fallback, query-param overrides, and blank-param handling for both the editor and public dashboard pages
- Suppress a spurious dialyzer warning in the Gettext-generated module so `mix lint` is clean

## Checklist

- [x] I have linked a GitHub issue using "Closes/Fixes/Resolves #<id>" (required)
- [x] I have followed the project's coding standards
- [x] Tests added or updated to cover changes
- [x] All tests pass locally (mix test)
- [x] Code formatted (mix format)
- [x] Dialyzer is clean (mix dialyzer)

### CODE REVIEW

File: .dialyzer_ignore.exs [hunk 1]
```diff
@@ -1 +1,5 @@
-[]
+[
+  # Gettext.Plural macro-generated code triggers a spurious type mismatch on the
+  # `Expo.PluralForms` struct argument under newer Elixir/Dialyzer versions.
+  {"lib/lotus/web/gettext.ex"}
```
Comment (tugayac) [inline .dialyzer_ignore.exs:4]: Problem possibly coming from the library itself, so ignoring for now.
